spring:
    application:
        name: prs-zuul
    sleuth:
        sampler:
            percentage: 1.0
    zipkin:
        base-url: http://localhost:9411
server:
    address: 0.0.0.0
    port: 8100
zuul:
    ignoredServices: '*'
    prefix: /api
    routes:
        feed:
            path: /logminer/**
            serviceId: PRS-LOGMINER
eureka:
    instance:
        hostname: prs-zuul
    client:
        serviceUrl:
            defaultZone: http://root:asdf@peer1:8000/eureka/,http://root:asdf@peer2:8001/eureka/,http://root:asdf@peer3:8002/eureka/

