server:
    port: 9001
    address: 0.0.0.0
spring:
    application:
        name: prs-recommend
    redis:
        host: localhost
        port: 6379
    data:
        elasticsearch:
            cluster-name: elasticsearch
            cluster-nodes: 127.0.0.1:9300
            repositories:
                enabled: true
eureka:
    instance:
        hostname: prs-recommend
    client:
        serviceUrl:
            defaultZone: http://root:asdf@peer1:8000/eureka/,http://root:asdf@peer2:8001/eureka/,http://root:asdf@peer3:8002/eureka/
